name: quick_ping
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.3
  #to show network image
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  emoji_picker_flutter: ^4.3.0
  #notification
  # firebase_messaging: ^15.2.4
  http: ^1.3.0
  brain_fusion: 
  flutter_dotenv: ^5.2.1
  translator: ^1.0.3+1
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  flutter_email_sender: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - images/
