// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBglhhRYsdsy1n464GlCulBl41tnrGd-BU',
    appId: '1:1003940301634:android:7151eb03b6cc5d019656db',
    messagingSenderId: '1003940301634',
    projectId: 'quickping-abc7b',
    storageBucket: 'quickping-abc7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3k4KGIfo__Rq6NWYVvHEJn3BAbY41qfk',
    appId: '1:1003940301634:ios:2ff101fcf05fa2c69656db',
    messagingSenderId: '1003940301634',
    projectId: 'quickping-abc7b',
    storageBucket: 'quickping-abc7b.firebasestorage.app',
    androidClientId: '1003940301634-4bjqecgig9gkagedggrc5cf71r2a8t4f.apps.googleusercontent.com',
    iosClientId: '1003940301634-sd910mj0i7apc4qmdknf2lq5cerm0u4o.apps.googleusercontent.com',
    iosBundleId: 'com.harish.quickPing',
  );

}